development:
  adapter: mysql2
  host: localhost
  database: rental_connect_dev
  username: rental
  password: secret
  port: 3306

test:
  adapter: mysql2
  host: localhost
  database: rental_connect_test
  username: rental
  password: secret
  port: 3306